### ISSUE TITLE
'YFI' is not a valid Coin

### ISSUE THREAD

**Issue by lebseu** [goincrypto/cryptocom-exchange#14]
I tried to run the example code:
```
import asyncio
import cryptocom.exchange as cro

async def main():
    account = cro.Account(from_env=True)
    data = await account.get_balance()
    print(f'Account balance {data}')

asyncio.run(main())
```
And the following exception occurred:

```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test.py", line 14, in main
    data = await account.get_balance()
  File "/Users/../.local/share/virtualenvs/cryptocom-exchange-DrEz_xtF/lib/python3.8/site-packages/cryptocom/exchange/private.py", line 25, in get_balance
    data = await self.api.post(
  File "/Users/../.local/share/virtualenvs/cryptocom-exchange-DrEz_xtF/lib/python3.8/site-packages/cryptocom/exchange/api.py", line 135, in post
    return await self.request('post', path, data=data, sign=sign)
  File "/Users/../.local/share/virtualenvs/cryptocom-exchange-DrEz_xtF/lib/python3.8/site-packages/cryptocom/exchange/api.py", line 95, in request
    raise ApiError(
cryptocom.exchange.api.ApiError: Error: {'id': 5857, 'method': 'private/get-account-summary', 'code': 10002, 'message': 'UNAUTHORIZED'}. Status: 401
(cryptocom-exchange) (base) ➜  mycode git:(master) ✗ python test.py
ValueError: 'YFI' is not a valid Coin

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test.py", line 14, in main
    data = await account.get_balance()
  File "/Users/../.local/share/virtualenvs/cryptocom-exchange-DrEz_xtF/lib/python3.8/site-packages/cryptocom/exchange/private.py", line 27, in get_balance
    return {
  File "/Users/../.local/share/virtualenvs/cryptocom-exchange-DrEz_xtF/lib/python3.8/site-packages/cryptocom/exchange/private.py", line 28, in <dictcomp>
    Coin(bal['currency']): Balance(
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/enum.py", line 304, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/enum.py", line 595, in __new__
    raise exc
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/enum.py", line 579, in __new__
    result = cls._missing_(value)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/enum.py", line 608, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'YFI' is not a valid Coin
```

**Comment by mortyspace** [comment]
Hi, looking into new PR, that will solve this
