### ISSUE TITLE
cryptocom.exchange.api.ApiError: Cannot connect to host https://api.crypto.com/v2/

### ISSUE THREAD

**Issue by Neuroforge** [goincrypto/cryptocom-exchange#19]
Hello,

Here is a bit a of a noob question, but could be relevant to other people.

I am running a simple test script to explore the Crypto.com api. There appears to be some issue with SSL and i cannot see anything in the Crypto.com documentation or the cryptocom-exchange documentation/tests to handle such issues.

The cryptocom-exchange was install from pip.

The example code being used is as follows...

```
import asyncio
import cryptocom.exchange as cro
import pprint
pp = pprint.PrettyPrinter(indent=4)

apiKey = "API_KEY"
appSecret = "SECRET_VALUE"
async def main():
    account = cro.Account(api_key=apiKey, api_secret=appSecret)
    balances = await account.get_balance()
    pp.print(balances)

asyncio.run(main())
```

The API configuration is pretty vanilla....

<img width="610" alt="Screenshot 2020-12-25 at 2 44 00 am" src="https://user-images.githubusercontent.com/1474186/103097367-1bf5e480-465b-11eb-981e-d8e46b4ed6ee.png">

This is the error output.

```
Traceback (most recent call last):
  File "/Users/daniel/Documents/traderBot/Crypto/crypto-env/lib/python3.7/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 981, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1009, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/sslproto.py", line 530, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 774, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/daniel/Documents/exchangeTest/crypto-env/lib/python3.7/site-packages/cryptocom/exchange/api.py", line 91, in request
    headers={'content-type': 'application/json'}
  File "/Users/daniel/Documents/exchangeTest/crypto-env/lib/python3.7/site-packages/aiohttp/client.py", line 521, in _request
    req, traces=traces, timeout=real_timeout
  File "/Users/daniel/Documents/traderBot/Crypto/crypto-env/lib/python3.7/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/daniel/Documents/traderBot/Crypto/crypto-env/lib/python3.7/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/daniel/Documents/traderBot/Crypto/crypto-env/lib/python3.7/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/Users/daniel/Documents/traderBot/Crypto/crypto-env/lib/python3.7/site-packages/aiohttp/connector.py", line 1032, in _create_direct_connection
    client_error=client_error,
  File "/Users/daniel/Documents/traderBot/Crypto/crypto-env/lib/python3.7/site-packages/aiohttp/connector.py", line 971, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.crypto.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "exchange.py", line 15, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "exchange.py", line 10, in main
    balances = await account.get_balance()
  File "/Users/daniel/Documents/traderBot/Crypto/crypto-env/lib/python3.7/site-packages/cryptocom/exchange/private.py", line 33, in get_balance
    data = await self.api.post('private/get-account-summary')
  File "/Users/daniel/Documents/traderBot/Crypto/crypto-env/lib/python3.7/site-packages/cryptocom/exchange/api.py", line 136, in post
    return await self.request('post', path, data=data, sign=sign)
  File "/Users/daniel/Documents/traderBot/Crypto/crypto-env/lib/python3.7/site-packages/cryptocom/exchange/api.py", line 99, in request
    raise ApiError(f"Cannot connect to host {self.root_url}")
cryptocom.exchange.api.ApiError: Cannot connect to host https://api.crypto.com/v2/
```

**Comment by Neuroforge** [comment]
Solution is with Python not the api.

https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org
