### ISSUE TITLE
401 Unauthorized on trade commands

### ISSUE THREAD

**Issue by florinteodorescu** [goincrypto/cryptocom-exchange#23]
import asyncio
import cryptocom.exchange as cro

async def main():
    order_ids = []
    exchange = cro.Exchange()
    # ensure pairs fresh from exchange
    await exchange.sync_pairs()
    price = await exchange.get_price(cro.pairs.CRO_USDT)
    print(price)
    account = cro.Account(api_key='myKEY, api_secret='mySecret')
    await account.sync_pairs()
    data = await account.get_balance()
    #print(f'Account balance {data}')

    orderId =  await account.buy_limit(cro.pairs.CRO_USDT, quantity=1, price=0.05)
    print(f'Order {orderId}')

Hi, I've been trying to play around with this library and can't seem to make it work. My code is the one above.
Its printing the CRO price, also the balance (not visible in the below output) but the buy_limit command always fails. The fact that balance works makes me think that the keys are correct, and I've also checked that the API keys have "trading" enabled. Any ideea what I'm doing wrong?

0.18915
Traceback (most recent call last):
  File "/Users/teodores/hummbflask/hummbflask.py", line 28, in <module>
    asyncio.run(main())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/teodores/hummbflask/hummbflask.py", line 24, in main
    orderId =  await account.buy_limit(cro.pairs.CRO_USDT, quantity=1, price=0.05)
  File "/Users/teodores/Library/Python/3.8/lib/python/site-packages/cryptocom/exchange/private.py", line 120, in buy_limit
    return await self.create_order(
  File "/Users/teodores/Library/Python/3.8/lib/python/site-packages/cryptocom/exchange/private.py", line 111, in create_order
    resp = await self.api.post('private/create-order', {'params': data})
  File "/Users/teodores/Library/Python/3.8/lib/python/site-packages/cryptocom/exchange/api.py", line 136, in post
    return await self.request('post', path, data=data, sign=sign)
  File "/Users/teodores/Library/Python/3.8/lib/python/site-packages/cryptocom/exchange/api.py", line 95, in request
    raise ApiError(
cryptocom.exchange.api.ApiError: Error: {'id': 4903, 'method': 'private/create-order', 'code': 10002, 'message': 'UNAUTHORIZED'}. Status: 401. Json params: {'params': {'instrument_name': 'CRO_USDT', 'side': 'BUY', 'type': 'LIMIT', 'time_in_force': 'GOOD_TILL_CANCEL', 'exec_inst': '', 'quantity': '1.000', 'price': '0.05000'}, 'method': 'private/create-order', 'nonce': 1619099175855, 'api_key': 'P...', 'id': 4903, 'sig': 'bb3548c271a4558c7eeda403283b8d4c63bd77a5b60a64151961d8044c68aa1c'}

**Comment by florinteodorescu** [comment]
It worked after deleting the keys and adding them again
